# Generated by Django 3.1.4 on 2021-01-21 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('streaming_date', models.DateTimeField()),
                ('streaming_duration_min', models.IntegerField()),
                ('streaming_link', models.URLField()),
                ('min_book_client', models.IntegerField()),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='real_estate.realestate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
