# Generated by Django 3.1.4 on 2021-01-28 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20210128_1230'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate'),
        ),
    ]
