# Generated by Django 3.1.4 on 2021-01-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210128_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='min_book_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='streaming_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='streaming_duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='streaming_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
