# Generated by Django 3.1.4 on 2021-01-28 03:30

import api.models.real_estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='id',
            field=models.CharField(default=api.models.real_estate.models.hex_uuid, max_length=100, primary_key=True, serialize=False),
        ),
    ]
