# Generated by Django 3.1.4 on 2021-01-20 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_remove_client_booked_tour'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tour.tour')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
