# Generated by Django 3.1.4 on 2021-01-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='booked_tour',
        ),
    ]
